# YuvaSetu AI — Official & Verified Indian Educational Datasets
# Sources: DIKSHA Portal (diksha.gov.in), Ministry of Education (education.gov.in), 
# UDISE+ 2023-24 (udiseplus.gov.in), AISHE (aishe.gov.in), PM-eVIDYA & NITI Aayog (aim.gov.in)

CHALLENGES = [
    {
        "id": 1,
        "title": "Gangetic Basin Foundational STEM & DIKSHA Literacy Hub",
        "state": "Uttar Pradesh",
        "district": "Varanasi",
        "domain": "Education",
        "problem_statement": "Primary school kids across Varanasi & the Gangetic basin often struggle when switching from local dialects to standard science & math terms. DIKSHA digital content can help bridge early learning gaps.",
        "why_it_matters": "Building strong foundational math and reading skills in young children creates a solid foundation for lifelong learning, directly supporting NEP 2020 and NIPUN Bharat goals.",
        "required_skills": ["Python", "JavaScript", "NLP & Speech Recognition"],
        "suggested_skills": ["Digital India Bhashini APIs", "Gamified Learning Design", "Offline Mobile Sync"],
        "difficulty": "Medium",
        "beneficiaries": "14,200 primary school students across 36 PM Shri schools",
        "explorers_count": 482,
        "latitude": 25.3176,
        "longitude": 82.9739,
        "pillColor": "#30D158",
        "pillCategory": "Gangetic Basin",
        "gov_source": "DIKSHA Portal / diksha.gov.in & Ministry of Education (UDISE+)"
    },
    {
        "id": 2,
        "title": "North Bihar STEM & PM-eVIDYA Vernacular Learning Hub",
        "state": "Bihar",
        "district": "Patna",
        "domain": "Education",
        "problem_statement": "Schools in rural North Bihar need interactive, easy-to-understand science experiments in local languages so secondary students can fall in love with STEM subjects.",
        "why_it_matters": "Giving rural students access to quality STEM tools boosts higher education enrollment and aligns with PM-eVIDYA digital inclusion initiatives.",
        "required_skills": ["React", "Python", "Data Analytics"],
        "suggested_skills": ["AI Tutor Models", "Video Streaming Analytics", "UX Design"],
        "difficulty": "Hard",
        "beneficiaries": "28,500 students & 640 local educators",
        "explorers_count": 530,
        "latitude": 25.5941,
        "longitude": 85.1376,
        "pillColor": "#FF453A",
        "pillCategory": "North Bihar STEM Hub",
        "gov_source": "DIKSHA Datasets / diksha.gov.in & UDISE+ 2023-24"
    },
    {
        "id": 3,
        "title": "Saurashtra Renewable Energy & Marine STEM Skill Corridor",
        "state": "Gujarat",
        "district": "Rajkot",
        "domain": "Employment & Entrepreneurship",
        "problem_statement": "Polytechnic and college students in coastal Saurashtra want practical skills in solar power grid telemetry, wind energy systems, and green technology.",
        "why_it_matters": "Connecting youth skills with green energy industries creates high-paying local jobs under the Skill India Digital mission.",
        "required_skills": ["Embedded C / C++", "IoT Interfacing", "Python"],
        "suggested_skills": ["Solar Grid Telemetry", "Power Systems Modeling", "Time Series Forecasting"],
        "difficulty": "Hard",
        "beneficiaries": "8,900 polytechnic & ITI graduates",
        "explorers_count": 365,
        "latitude": 22.3039,
        "longitude": 70.8022,
        "pillColor": "#A2E635",
        "pillCategory": "Saurashtra Skill Zone",
        "gov_source": "AISHE Report / aishe.gov.in & Skill India Digital"
    },
    {
        "id": 4,
        "title": "MP Soybean Plateau Smart Agriculture & Youth Skill Zone",
        "state": "Madhya Pradesh",
        "district": "Indore",
        "domain": "Agriculture",
        "problem_statement": "Young agricultural entrepreneurs in Malwa & Soybean plateau regions require simple, mobile-friendly soil nutrient testing tools to reduce chemical costs.",
        "why_it_matters": "Smart farming saves soil health, cuts expense for family farms, and aligns with national PM-PRANAM organic soil targets.",
        "required_skills": ["Python", "Data Analytics", "Mobile App Development"],
        "suggested_skills": ["GIS Analytics", "Soil Chemistry Basics", "IoT Hardware"],
        "difficulty": "Medium",
        "beneficiaries": "19,200 young farmers across 48 villages",
        "explorers_count": 420,
        "latitude": 22.7196,
        "longitude": 75.8577,
        "pillColor": "#FF9500",
        "pillCategory": "MP Soybean Plateau",
        "gov_source": "DIKSHA Agri-Skill Portal & Ministry of Agriculture (data.gov.in)"
    },
    {
        "id": 5,
        "title": "Vidarbha Agro-Tech Vocational Skill Belt",
        "state": "Maharashtra",
        "district": "Nagpur",
        "domain": "Agriculture",
        "problem_statement": "Youth in Vidarbha agriculture hubs face seasonal underemployment. Micro-learning modules in drone crop mapping and drip irrigation help them start agro-services.",
        "why_it_matters": "Empowering rural youth with modern tech skills generates steady income and strengthens rural economic resilience.",
        "required_skills": ["Python", "IoT Interfacing", "Mobile App Development"],
        "suggested_skills": ["GIS & Spatial Analytics", "Drone Telemetry", "Hardware Maintenance"],
        "difficulty": "Medium",
        "beneficiaries": "16,400 rural youth & agri-entrepreneurs",
        "explorers_count": 412,
        "latitude": 21.1458,
        "longitude": 79.0882,
        "pillColor": "#64D2FF",
        "pillCategory": "Vidarbha Skill Belt",
        "gov_source": "ICAR Network & Skill India Digital / data.gov.in"
    },
    {
        "id": 6,
        "title": "Odisha Coastal Belt PM Shri School Resilient Learning Network",
        "state": "Odisha",
        "district": "Bhubaneswar",
        "domain": "Education",
        "problem_statement": "Coastal schools along Odisha experience severe monsoon storms. Digital offline-first learning kits ensure school continuity even during power outages.",
        "why_it_matters": "Disaster-resilient digital education guarantees uninterrupted learning for children in vulnerable coastal communities.",
        "required_skills": ["JavaScript", "Offline PWA", "Web Development"],
        "suggested_skills": ["Low-bandwidth Sync", "Educational Content Caching", "UX Design"],
        "difficulty": "Medium",
        "beneficiaries": "22,000 coastal school students",
        "explorers_count": 450,
        "latitude": 20.2961,
        "longitude": 85.8245,
        "pillColor": "#00F0FF",
        "pillCategory": "Odisha Coastal Belt",
        "gov_source": "DIKSHA Odisha Portal / diksha.gov.in & PM Shri Schools"
    },
    {
        "id": 7,
        "title": "Rayalaseema Digital AI Literacy & Atal Tinkering Network",
        "state": "Andhra Pradesh",
        "district": "Anantapur",
        "domain": "Education",
        "problem_statement": "Students in Rayalaseema schools are eager to learn AI and robotics, but need hands-on kit modules and simplified tutorials in Telugu.",
        "why_it_matters": "Democratizing access to Atal Innovation Labs sparks creativity early and prepares students for future tech careers.",
        "required_skills": ["JavaScript", "Python", "Robotics Basics"],
        "suggested_skills": ["Arduino / Raspberry Pi", "Computer Vision", "Web Dev"],
        "difficulty": "Medium",
        "beneficiaries": "11,800 secondary school students across 28 ATL labs",
        "explorers_count": 395,
        "latitude": 14.6819,
        "longitude": 77.6006,
        "pillColor": "#FFD60A",
        "pillCategory": "Rayalaseema Zone",
        "gov_source": "Atal Innovation Mission / aim.gov.in & DIKSHA AP"
    },
    {
        "id": 8,
        "title": "Ladakh High-Altitude STEM & Solar Innovation Zone",
        "state": "Ladakh",
        "district": "Leh",
        "domain": "Education",
        "problem_statement": "High-altitude schools in Leh & Kargil face long winter isolation. Vernacular solar-powered offline learning hubs can keep science learning active year-round.",
        "why_it_matters": "Ensuring 100% educational continuity in remote border territories supports equitable national youth empowerment.",
        "required_skills": ["Python", "Embedded Systems", "Solar Micro-Grids"],
        "suggested_skills": ["Offline Mesh Network", "Thermal Insulation Tech", "Interactive Content"],
        "difficulty": "Hard",
        "beneficiaries": "6,400 students across high-altitude border hamlets",
        "explorers_count": 510,
        "latitude": 34.1526,
        "longitude": 77.5771,
        "pillColor": "#38BDF8",
        "pillCategory": "Ladakh High-Altitude Zone",
        "gov_source": "Ministry of Education / education.gov.in & DIKSHA UT Ladakh"
    },
    {
        "id": 9,
        "title": "Kamrup Digital Literacy & DIKSHA Bhashini Vernacular Shield",
        "state": "Assam",
        "district": "Kamrup",
        "domain": "Digital Inclusion",
        "problem_statement": "Women-led Self-Help Groups and local students in Kamrup require voice-assisted Assamese digital tools to prevent online financial scams.",
        "why_it_matters": "Financial and digital safety builds trust in digital public infrastructure, empowering rural women entrepreneurs under DAY-NRLM.",
        "required_skills": ["Cybersecurity Basics", "React", "UX Design"],
        "suggested_skills": ["Assamese NLP", "Behavioral Nudges", "Fintech API"],
        "difficulty": "Easy",
        "beneficiaries": "600 SHG groups & 7,200 local learners",
        "explorers_count": 195,
        "latitude": 26.1445,
        "longitude": 91.7362,
        "pillColor": "#BF5AF2",
        "pillCategory": "Kamrup Vernacular Hub",
        "gov_source": "DIKSHA Bhashini Portal / diksha.gov.in & DAY-NRLM"
    },
    {
        "id": 10,
        "title": "Precision Agriculture & Soil Analytics for Punjab Smallholders",
        "state": "Punjab",
        "district": "Ludhiana",
        "domain": "Agriculture",
        "problem_statement": "Farmers in Ludhiana district need easy real-time soil health feedback to optimize fertilizer usage and save groundwater.",
        "why_it_matters": "Protecting soil organic matter in India's agricultural heartland protects food security for 1.4 billion citizens.",
        "required_skills": ["Python", "IoT Interfacing", "Data Analytics"],
        "suggested_skills": ["GIS & Spatial Analytics", "Mobile App Development", "Soil Chemistry"],
        "difficulty": "Medium",
        "beneficiaries": "12,400 smallholder farmers across 42 villages",
        "explorers_count": 342,
        "latitude": 30.9010,
        "longitude": 75.8573,
        "pillColor": "#FF7722",
        "pillCategory": "Punjab Agri Zone",
        "gov_source": "Ministry of Agriculture / data.gov.in (Soil Health Card Scheme)"
    }
]
